### ISSUE TITLE
About the dependent packages version

### ISSUE THREAD

**Issue by EcustBoy** [Tsinghua-MARS-Lab/InterSim#1]
Hi author~ could you please indicate the suitable version of the detailed dependent packages? e.g.  the tensorflow package

**Comment by larksq** [comment]
Hi,

InterSim does not limit the versions of dependent packages. To the best of our knowledge, any version of TensorFlow (or Pytorch) that suits your CUDA should be good. One exception is the gym package. Some higher versions might not be compatible. We suggest following the setup.py to install gym==0.18.3. And InterSim does require a Python3 environment for pickle management.

Now relax and enjoy. Further questions are always welcome.
