### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by everwind** [Tsinghua-MARS-Lab/InterSim#2]
FileNotFoundError: [Errno 2] No such file or directory: './prediction/M2I/relation_predictor/pretrained/infPred.NoTail.timeOffset.loopx2.IA.v2x.NonStop20.noIntention.0424.model.60.bin'

**Comment by everwind** [comment]
i can not find the " relation prediction model" in this project

**Comment by larksq** [comment]
Please follow the readme and download the pre-trained model from this google drive link: https://drive.google.com/drive/folders/1oDkIcttHwcaFSir1L02tp2U8mX20NEk1. Due to the agreement of Waymo, you might need to request access (and I will grant it ASAP).

Also, follow the readme to compile the Cython script before you use the relation predictor.

**Comment by cisimon7** [comment]
Hello, I suppose there's also a link to the file that resolves the error message below. 

`FileNotFoundError: [Errno 2] No such file or directory: './prediction/M2I/marginal_prediction/pretrained/8S.raster.maskNonInfFilterSteadyP5.Loopx10.0410.model.9.bin'`

I was trying to use a custom planner when the error occurred. Perhaps you could make available also, the links to the other files as listed as part of the model_path as the above link only has the `relation_pred` file
```
self.model_path = {
            'guilded_m_pred': './prediction/M2I/guilded_m_pred/pretrained/LowSpeedGoalDn.model.30.bin',
            'marginal_pred': './prediction/M2I/marginal_prediction/pretrained/8S.raster.maskNonInfFilterSteadyP5.Loopx10.0410.model.9.bin',
            'relation_pred': './prediction/M2I/relation_predictor/pretrained/infPred.NoTail.timeOffset.loopx2.IA.v2x.NonStop20.noIntention.0424.model.60.bin',
            'variety_loss_prediction': './prediction/M2I/variety_loss_prediction/pretrained/model.26.bin',
            'marginal_pred_tnt': './prediction/M2I/marginal_prediction_tnt/pretrained/tnt.model.21.bin'
        }
```
and what is the difference between each model please?
