### ISSUE TITLE
Error in runing:  goal is None in get_reroute_traj

### ISSUE THREAD

**Issue by EcustBoy** [Tsinghua-MARS-Lab/InterSim#3]
Hi author~  I launch the simulator with Waymo dataset as  the tutorial in readme. I choose running mode=0 or 1, but when the "step" function in drive.py begins , the following error will occur when env agent runs **get_reroute_traj** function, it seems like the env agent can't get it's goal so that it fails to search the new route?  
I'm sure that my environment dependencies and datasets are installed correctly. So I would like to consult for advice, what is the possible reason?  have you encountered similar error before? many thanks~

![image](https://user-images.githubusercontent.com/32817744/202349792-39e6816d-a2c6-4483-a23b-592161120ce3.png)

**Comment by larksq** [comment]
Could you please share the following information so that I can repeat and check the problem?
- Dataset using
- File name
- Scenario index or id
Does it crash for one specific scene or every scene?

**Comment by EcustBoy** [comment]
Thanks so much for your reply which reminds me I set the  tf_example_dir in config.py as  waymo **test** data, after changing to **training** or **validation** data, the above error disappear.   

#######################################

But another error occurs during debugging:
I found if I choose Waymo **training** data,  and choose the first tfrecord file in **training** part(**index=0 in the 1000 tf files**) and **scenario index = 230** (same as the default value in original code ), then when base planner executes, it print "TEST OFF ROAD!!!!!!!!" :
![e552e54a-167a-4621-811d-96fd36cb05ad](https://user-images.githubusercontent.com/32817744/202864888-8994893a-9179-47b1-9042-e62acf2ad54b.jpeg)

and the terminal outputs:
![10d6dfd4-97f3-46c6-8047-7a4f89aa095e](https://user-images.githubusercontent.com/32817744/202865357-e1479aaf-730c-4dcd-b83d-6dc1a23c3636.jpeg)

Then I continue running, the error occurs:
![f9116dd9-dc82-4363-8648-64b92de5979e](https://user-images.githubusercontent.com/32817744/202864952-7cbc5429-ce7b-4eae-9834-0ceece9bb465.jpeg)



it seems like ego car fails to find lane sequence as the new route? 
Then I choose waymo **validation** data(**index = 0 in the 150 files, while scenario index, same as the default value in original code, is 230 too**),  no errors appear
I wonder if this is normal？

**Comment by larksq** [comment]
The warning of 'TEST OFF ROAD' is normal, but not the crash during simulation. I just updated the planners after additional debugs. Could you please try it again and see if it still crashes for the same scenario?
