### ISSUE TITLE
utils_cython not found error

### ISSUE THREAD

**Issue by EnnaSachdeva** [Tsinghua-MARS-Lab/InterSim#4]
After compiling the cython scripts, and running **python sim.py** gives the following error-

ModuleNotFoundError: No module named 'prediction.M2I.marginal_prediction.src.utils_cython'

**Comment by swb19** [comment]
> After compiling the cython scripts, and running **python sim.py** gives the following error-
> 
> ModuleNotFoundError: No module named 'prediction.M2I.marginal_prediction.src.utils_cython'

Hello, I also encountered a similar problem. Have you solved it?

**Comment by larksq** [comment]
Try to also compile the utils_cython in marginal_prediction as follows?
`cd prediction/M2I/marginal_prediction/src/` `cython -a utils_cython.pyx && python setup.py build_ext --inplace`

**Comment by swb19** [comment]
> Try to also compile the utils_cython in marginal_prediction as follows? `cd prediction/M2I/marginal_prediction/src/` `cython -a utils_cython.pyx && python setup.py build_ext --inplace`

Hello, I tried the above commands but found some errors as follows, have you encountered similar errors?
![Screenshot from 2022-12-24 17-41-46](https://user-images.githubusercontent.com/58935575/209430277-98ee5c89-2cfb-4da0-9e81-53400f3e8ab8.png)

**Comment by larksq** [comment]
I think these are just some warnings from Cython that do not block the compiling process.

**Comment by swb19** [comment]
> 

Thank you very much, but I still get `No module named 'prediction.M2I.relation_predictor.src.utils_cython'` error when I try to run `python sim.py` after compiling the utils_cython.

**Comment by larksq** [comment]
Could you run the same script in the `relation_predictor/src` folder and try again?
`cd prediction/M2I/relation_predictor/src/` `cython -a utils_cython.pyx && python setup.py build_ext --inplace`
