### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by jessapinkman** [Tsinghua-MARS-Lab/InterSim#5]
hi, i wonder if your code is really complete in detect_relations_func.py ？cause i cannot see the def “**check_collision_for_two_agents_rotate_and_dist_check**” anywhere.

**Comment by larksq** [comment]
Thank you for pointing this out. The detect_relations_func.py is not complete indeed and was just deleted.

You might be looking for a script for auto-labeling the scenarios for ground truth relation labels. If so, you might want to check `process_interactive_multi.py` as an example to loop all scenarios and save the ground truth relation labels for training a relation predictor. 

I used this py script long ago. There might be some outdated broken functions here and there. Please let me know if this script still works well and maybe solve your problems. Moreover, I am constantly experimenting with different options to generate these labels with better qualities. If you are interested in discussing and discovering this flank, you are more than welcome to contact me, by Email perhaps.
