### ISSUE TITLE
Error in "npm run dev"

### ISSUE THREAD

**Issue by salt0107fish** [Tsinghua-MARS-Lab/InterSim#7]
Hi~ Thank you for your work!
When I run **npm run dev** for a local client, there are some errors in my terminal, such as:
`
  source/js/zui.js
  line 3    col 3   'class' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 11   col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 12   col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 39   col 3   'class' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 66   col 20  Class properties must be methods. Expected '(' but instead saw '='.
  line 72   col 18  Class properties must be methods. Expected '(' but instead saw '='.
  line 73   col 10  Class properties must be methods. Expected '(' but instead saw ':'.
  line 76   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 77   col 14  'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 84   col 5   Expected an assignment or function call and instead saw an expression.
  line 84   col 11  Missing semicolon.
  line 84   col 36  Missing semicolon.
  line 90   col 5   Expected an assignment or function call and instead saw an expression.
  line 90   col 11  Missing semicolon.
  line 90   col 32  Missing semicolon.
  line 94   col 5   Expected an assignment or function call and instead saw an expression.
  line 94   col 11  Missing semicolon.
  line 94   col 34  Missing semicolon.
  line 100  col 17  Missing semicolon.
  line 102  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 107  col 24  Missing semicolon.
  line 131  col 26  Missing semicolon.
  line 133  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 134  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 138  col 23  Missing semicolon.
  line 140  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 141  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 145  col 34  Missing semicolon.
  line 146  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 151  col 36  Missing semicolon.
  line 153  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 160  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 161  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 166  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 167  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 168  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 175  col 27  Missing semicolon.
  line 181  col 19  Missing semicolon.
  line 183  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 196  col 20  Missing semicolon.
  line 198  col 7   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 199  col 12  'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 207  col 12  Missing semicolon.
  line 214  col 19  Missing semicolon.
  line 220  col 3   Expected ')' to match '(' from line 1 and instead saw 'Two'.
  line 220  col 16  Unrecoverable syntax error. (98% scanned).

  ✖  22 errors
  ⚠  24 warnings
`
After that, the html opens normally, and the visualization results seem to be normal, too.
I didn't modify any part of the program. I want to know the possible reason for these errors. Do they have any influence on the simulation results?
Thank you very much~

**Comment by larksq** [comment]
As long as the pages and scenes can be rendered, all js warnings and errors can be ignored. And they have no influence at all on the simulation results.

**Comment by salt0107fish** [comment]
> As long as the pages and scenes can be rendered, all js warnings and errors can be ignored. And they have no influence at all on the simulation results.

Thank you for your reply!
