### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by may210297** [Tsinghua-MARS-Lab/InterSim#8]
Hello MARS! when I run the `python sim.py --max_scenarios=5`, return the error:
"ModuleNotFoundError: No module named 'prediction.M2I.relation_predictor.src.utils_cython'".

dataset is nuplan.

Hope for reply. Thanks!

**Comment by larksq** [comment]
Hi Yuan, 

it looks like you did not compile the Cython before using it. 
Try to follow the readme and run 
`cd prediction/M2I/relation_predictor/src/` and 
`cython -a utils_cython.pyx && python setup.py build_ext --inplace`

Sorry for the compiling trouble. We are planning to update InterSim and replace this dependency probably next month.
So stay tuned.

**Comment by may210297** [comment]
Hi, Qiao,
Sorry for neglecting the readme.md. Thank you!

**Comment by larksq** [comment]
No problem. Glad to help.
